export const FB = {
  global_: {
    nom: "Institut Lyne Beauty",
    tagline: "Onglerie & Coiffeur — Fribourg",
    annonce: "✨ <strong>Offre Bienvenue :</strong> -10% sur votre première prestation. Demandez aussi votre carte de fidélité à l'institut.",
    telephone: "+41 77 998 64 26",
    whatsapp: "https://wa.me/41779986426?text=Bonjour%2C%20je%20viens%20du%20site%20internet.%20Je%20souhaite%20vous%20poser%20une%20question%20sur%20%3A%20",
    instagram: "https://www.instagram.com/lynebeauty18/",
    lien_reservation: "https://lynebeauty.ch/",
    adresse: "Rue de Zaehringen 4",
    ville: "1700 Fribourg",
    meta_title: "Institut Lyne Beauty Onglerie & Coiffeur — Fribourg | Pose de gel, Tresses",
    meta_desc: "Institut Lyne Beauty Onglerie & Coiffeur à Fribourg (Rue de Zaehringen 4) — Expertise Onglerie (pose gel, vernis semi-permanent) et Coiffure Afro/Classique. Réservez sur brevo.com.",
  },
  nav: {
    liens: [
      { label: "Mes Rituels", ancre: "#universes" },
      { label: "Onglerie", ancre: "#onglerie" },
      { label: "Pédicure", ancre: "#pedicure" },
      { label: "Coiffure", ancre: "#coiffure" },
      { label: "L'Institut", ancre: "#about" },
      { label: "Le Salon", ancre: "#le-salon" },
      { label: "Contact", ancre: "#contact" },
    ],
    cta: "Réserver ma parenthèse",
  },
  hero: {
    eyebrow: "Institut · Fribourg",
    h1_normal: "Votre ",
    h1_italic: "parenthèse de sérénité",
    h1_suite: " au cœur de Fribourg",
    h2: "Franchissez le seuil de mon boudoir. Jocelyne signe chaque <a href=\"#onglerie\" class=\"text-link\">pose</a>, chaque <a href=\"#coiffure\" class=\"text-link\">tresse</a> et chaque <a href=\"#pedicure\" class=\"text-link\">soin</a> avec la précision d'une orfèvre et la chaleur d'une confidente.",
    cta1: "Réserver votre instant",
    cta2: "Découvrir mes rituels",
    badge: "Lâcher-prise · Avec ou sans RDV",
    marquee: "Ongles Signature ✦ Lâcher-prise ✦ Tresses & Tissages ✦ Confiance ✦ Vernis Semi-Permanent ✦ Bien-être ✦ Coiffure Afro ✦ Pédicure Spa ✦",
    images: ["img/hero.webp", "img/hero1.webp", "img/hero2.webp"],
  },
  sectionUniverses: {
    eyebrow: "Vos instants sur-mesure",
    titre: "Mes Rituels <em>signature</em>",
    intro: "Je vous invite à découvrir une maîtrise globale de votre bien-être : l'art délicat de l'<a href=\"#onglerie\" class=\"text-link\" style=\"color:var(--bg-warm);\">onglerie</a>, le soin profond de la <a href=\"#pedicure\" class=\"text-link\" style=\"color:var(--bg-warm);\">pédicure</a> et la virtuosité de la <a href=\"#coiffure\" class=\"text-link\" style=\"color:var(--bg-warm);\">coiffure</a>. Une triple expertise, pour une sérénité totale.",
    cartes: [
      { tagline: "Rituel I · L'Élégance des mains", h3: "L'Onglerie", desc: "Pose gel, acrylique, vernis semi-permanent. Laissez vos mains révéler votre personnalité avec une tenue irréprochable.", lien: "#onglerie", image: "img/pro4.webp" },
      { tagline: "Rituel II · La Douceur des pieds", h3: "La Pédicure", desc: "Soin profond, gommage et massage relaxant. Une parenthèse de légèreté absolue pour vous ancrer dans le présent.", lien: "#pedicure", image: "img/pedicure.webp" },
      { tagline: "Rituel III · La Couronne sublimée", h3: "La Coiffure", desc: "Tresses, tissages, colorations. Confiez-moi vos cheveux pour révéler votre nature profonde, en toute sérénité.", lien: "#coiffure", image: "img/tresses.webp" },
    ],
  },
  sectionOnglerie: {
    eyebrow: "L'Élégance · Pose & Nail Art",
    h2_normal: "Sublimez vos mains avec",
    h2_italic: "une signature qui <em>dure.</em>",
    lead: "Le luxe du gain de temps : vos mains restent impeccables pendant des semaines. Fini les retouches quotidiennes, vous vous réveillez déjà prête, avec une confiance absolue.",
    corps: "Dans mon <a href=\"#le-salon\" class=\"text-link\">écrin</a>, je ne fais pas simplement les ongles. Je compose. Pose gel, acrylique, semi-permanent ou nail art : chaque technique est exécutée avec la rigueur d'une joaillière et la patience d'une miniaturiste, dans le plus profond respect de votre ongle naturel. Vous repartirez avec des mains qui parlent pour vous.",
    steps: [
      { label: "1. Le Diagnostic :", texte: "J'analyse la nature de votre ongle pour choisir la technique idéale." },
      { label: "2. Le Soin Signature :", texte: "Une pose exécutée avec des produits haut de gamme et la précision d'une orfèvre." },
      { label: "3. Les Conseils :", texte: "Mes secrets d'après-soin pour prolonger la tenue et la brillance à la maison." },
    ],
    titre_tarifs: "Prestations Onglerie",
    note_tarifs: "Cliquez sur votre prestation pour réserver",
    filters: [
      { label: "Toutes les prestations", val: "all" },
      { label: "Gel", val: "gel" },
      { label: "Acrylique", val: "acrylique" },
      { label: "Classique & Soins", val: "classique" },
    ],
    cta1: "Voir les disponibilités",
    cta2: "En découvrir davantage",
    insta_cta: "Voir mes modèles d'ongles",
    images: ["img/onglerie.webp", "img/pro1.webp", "img/pro2.webp", "img/pro3.webp", "img/f5.webp"],
  },
  sectionPedicure: {
    eyebrow: "La Douceur · Pédicure Spa Fribourg",
    h2_normal: "Lâchez prise. Je prends",
    h2_italic: "soin de <em>chaque détail.</em>",
    lead: "Le luxe du gain de temps : une mise en beauté des pieds qui dure, pour un sentiment de pureté et de perfection à chaque instant.",
    corps: "Vos pieds vous portent chaque jour ; ils méritent ma plus belle attention. Je prends le temps de les préparer avec minutie, de les hydrater en profondeur, et de libérer vos tensions par un modelage doux. Que vous optiez pour la robustesse du gel, l'éclat d'un vernis semi-permanent, ou simplement une <a href=\"#universes\" class=\"text-link\">Pédicure Spa</a>, vous repartirez avec une sensation de légèreté absolue.",
    steps: [
      { label: "1. Le Diagnostic :", texte: "Écoute bienveillante de vos besoins (hydratation, callosités, esthétique)." },
      { label: "2. Le Soin Signature :", texte: "Pédicure spa avec gommage, massage relaxant et produits premiums." },
      { label: "3. Les Conseils :", texte: "Gestes simples pour garder une peau de bébé et prolonger la légèreté." },
    ],
    titre_tarifs: "Prestations Pédicure Spa",
    note_tarifs: "Cliquez sur votre prestation pour réserver",
    cta1: "Voir les disponibilités",
    cta2: "En découvrir davantage",
    images: ["img/pedicure.webp", "img/pedicure2.webp", "img/pied.webp"],
  },
  sectionCoiffure: {
    eyebrow: "La Couronne · Coiffure Afro & Classique",
    h2_normal: "Révélez votre nature,",
    h2_italic: "en toute <em>confiance.</em>",
    lead: "Le luxe du gain de temps : une coiffure protectrice, un tissage ou un lissage parfaitement exécuté vous libère l'esprit. Vous êtes prête à conquérir votre journée.",
    corps: "Dans mon atelier, la coiffure est avant tout un échange. Je vous écoute, j'analyse avec bienveillance la nature de vos cheveux, et nous décidons ensemble de ce qui vous sublimera le mieux. Découvrez l'atmosphère de mon <a href=\"#le-salon\" class=\"text-link\">salon dédié</a>.",
    steps: [
      { label: "1. Le Diagnostic :", texte: "Étude de votre cuir chevelu et de la texture de vos cheveux." },
      { label: "2. Le Soin Signature :", texte: "Exécution minutieuse sans douleur, avec des mèches et produits de haute qualité." },
      { label: "3. Les Conseils :", texte: "Routine d'hydratation (foulard en satin, huiles) pour faire durer votre couronne." },
    ],
    titre_tarifs: "Prestations Atelier Coiffure",
    note_tarifs: "Cliquez sur votre prestation pour réserver",
    filters: [
      { label: "Toutes les prestations", val: "all" },
      { label: "Avec extensions", val: "avec-ext" },
      { label: "Sans extensions", val: "sans-ext" },
      { label: "Soins & Classique", val: "soins" },
    ],
    cta1: "Voir les disponibilités",
    cta2: "En découvrir davantage",
    insta_cta: "Voir mes coiffures",
    images: ["img/tresses.webp", "img/tressep.webp", "img/tresses-femme3.webp", "img/tresses-homme4.webp", "img/f6-coiffure.webp"],
  },
  sectionAbout: {
    eyebrow: "L'Institut · La Confidente",
    h2: "Jocelyne, l'artisan de votre <em>beauté.</em>",
    lead: "Plus qu'un institut, je vous ouvre les portes d'un lieu où le geste est sûr, l'écoute attentive, et le sourire sincère.",
    corps1: "Mon parcours de 18 ans témoigne de cette quête d'excellence : <strong>2 années de formation certifiée</strong> (incluant un certificat anglais en pédicure), <strong>7 ans dédiés à sublimer vos <a href=\"#onglerie\" class=\"text-link\">ongles</a></strong>, et <strong>11 ans d'expertise dans l'art de la <a href=\"#coiffure\" class=\"text-link\">coiffure afro</a></strong>.",
    corps2: "Mon secret de fabrication ? L'alliance d'une élégance intemporelle et de l'utilisation exclusive de produits haut de gamme. Mais au-delà de la technique, mon obsession absolue est votre bien-être : ma plus belle réussite est de m'assurer que vous ressortiez de l'institut avec le sourire aux lèvres. Découvrez toutes les réponses à vos doutes dans <a href=\"#faq\" class=\"text-link\">mes questions fréquentes</a>.",
    signature: "— Jocelyne",
    stats: [
      { num: "18", suffix: "+", label: "Années d'expertise" },
      { num: "3", suffix: "", label: "Rituels maîtrisés" },
      { num: "100", suffix: "%", label: "Sourire & Hygiène" },
    ],
    badge_num: "18+",
    badge_lbl: "Ans d'expertise",
    images: ["img/jocelyne.webp", "img/jocelyne-coiffure.webp", "img/Jocelyn-pedicure.webp"],
  },
  sectionSalon: {
    eyebrow: "Mon Espace · Fribourg",
    h2: "Un boudoir dédié à votre <em>lâcher-prise.</em>",
    lead: "L'Institut Lyne Beauty a été conçu pour vous offrir bien plus qu'une simple prestation esthétique : c'est une parenthèse hors du temps. Dans une atmosphère chaleureuse aux nuances poudrées, chaque détail de décoration et d'aménagement a été pensé pour votre confort absolu.",
    corps: "De mes postes de <a href=\"#coiffure\" class=\"text-link\">coiffure</a> baignés de lumière à mes fauteuils de <a href=\"#pedicure\" class=\"text-link\">pédicure spa</a> massants, l'espace allie équipements de pointe et ambiance relaxante. Que ce soit pour une pose rapide ou une transformation complète de plusieurs heures, vous êtes ici chez vous. Asseyez-vous, détendez-vous, je m'occupe de tout.",
    tag: "L'Écrin",
    images: ["img/salon.webp", "img/coiffure-salon.webp", "img/pedicure-salon.webp"],
  },
  sectionReviews: {
    eyebrow: "Mots Doux",
    h2: "Celles qui ont <em>lâché prise.</em>",
    rating_text: "La confiance récompensée à Fribourg",
    lien_avis_url: "https://www.google.com/search?q=Institut+Lyne+Beauty+Onglerie+%26+Coiffeur+Avis",
    lien_avis_label: "Rédiger un avis",
  },
  sectionGallery: {
    eyebrow: "@lynebeauty18",
    h2: "Laissez-vous <em>inspirer</em>.",
    lien_label: "Me rejoindre sur Instagram →",
    images: ["img/f4.webp", "img/f2.webp", "img/f1.webp", "img/f3.webp", "img/coiffure4.webp", "img/feed6-onglerie.webp", "img/tresse-homme.webp", "img/prothesie-blanc.webp"],
  },
  sectionFaq: {
    eyebrow: "Questions Douces",
    h2: "Votre sérénité,<br>avant de <em>franchir la porte.</em>",
    intro: "J'ai rassemblé ici de quoi apaiser toutes vos interrogations sur mes rituels, mes tarifs et mon fonctionnement. Si vous avez d'autres doutes, n'hésitez pas à me contacter via mes <a href=\"#contact\" class=\"text-link\">coordonnées</a>.",
    cta: "M'écrire directement",
  },
  sectionReservation: {
    eyebrow: "Prendre rendez-vous",
    h2: "Votre <em>parenthèse</em> beauté.",
    texte: "Sélectionnez votre rituel et choisissez l'horaire qui vous convient. Notre agenda en ligne est disponible 24h/24.",
    cta: "Ouvrir l'agenda de l'institut",
    note: "Réservation rapide, simple et sécurisée.",
  },
  sectionContact: {
    eyebrow: "Contact · Fribourg",
    h2: "Venez pousser<br>la <em>porte.</em>",
    lead: "Un boudoir au plein cœur de Fribourg dans la vieille ville. Une vitrine rose poudré, une enseigne fleurie : vous ne pouvez pas la manquer.",
    h3_horaires: "Horaires d'ouverture",
  },
  footer_: {
    description: "L'Institut beauté de Fribourg dans la vieille ville, spécialiste de l'onglerie et de la coiffure afro & classique.",
    col1_titre: "Vos Rituels",
    col1_liens: [
      { label: "Onglerie Signature", href: "#onglerie" },
      { label: "Beauté des pieds", href: "#pedicure" },
      { label: "Atelier Coiffure", href: "#coiffure" },
    ],
    col2_titre: "Mon Histoire",
    col2_liens: [
      { label: "L'Écrin", href: "#about" },
      { label: "Questions Douces", href: "#faq" },
      { label: "Me Trouver", href: "#contact" },
      { label: "Réserver ma parenthèse", href: "https://lynebeauty.ch/" },
    ],
    col3_titre: "Me Trouver",
    copyright: "© 2026 Institut Lyne Beauty Onglerie & Coiffeur · Tous droits réservés",
    mentions: "Impressum & Mentions Légales",
    location: "Fribourg, Suisse",
  },
  horaires: {
    titre: "Horaires d'ouverture",
    jours: [
      { jour: "Lundi", heure: "14:00 — 19:00", ferme: false },
      { jour: "Mardi au Vendredi", heure: "09:00 — 19:00", note: "Pause : 12:00 — 13:00", ferme: false },
      { jour: "Samedi", heure: "08:30 — 17:00", ferme: false },
      { jour: "Dimanche", heure: "Fermé", ferme: true },
    ],
  },
  avis: [
    { auteur: "Valérie Sciboz", service: "Beauté des mains & Soin", texte: "Merci infiniment pour votre gentillesse et votre travail impeccable !" },
    { auteur: "Stefania B.", service: "Pose de gel & Finitions", texte: "Expérience incroyable, ongle magnifique et grande expertise. Très professionnel et aimable." },
    { auteur: "Patricia Hirt", service: "Pédicure Spa & Détente", texte: "Service impeccable et accueil chaleureux. Je vous le conseille musique à gogo selon choix. Bref j'ai passé un bon moment" },
    { auteur: "Raul Baeza", service: "Manucure Premium Homme", texte: "J'ai eu une expérience incroyable dans ce salon de manucure. Le personnel était très aimable et attentionné, l'ambiance était très relaxante, et le résultat final a dépassé mes attentes." },
    { auteur: "Gui F.", service: "Coiffure Sur-Mesure", texte: "Coiffeuse expérimentée, accueillante et très professionnelle! Elle sait répondre aux demandes des clients" },
    { auteur: "Anne-Laure", service: "Manucure Signature", texte: "J'ai passé un très bon moment et je suis ressortie de son institut avec une superbe manucure ! Jocelyne est très sympathique et fait attention aux détails. Je recommande vivement." },
    { auteur: "Javier Martinez", service: "Soin Esthétique Homme", texte: "Excellent travail, formidable ! & Joseline est très professionnelle et polie. Je la recommande vivement." },
    { auteur: "Camille R.", service: "Pose gel + Nail art", texte: "Une pose de gel d'une finesse rare. Jocelyne prend le temps, écoute, conseille. Trois semaines plus tard, mes ongles sont impeccables. Je ne change plus d'institut." },
  ],
  faqs: [
    { q: "Pourquoi la réservation en ligne est-elle privilégiée ?", r: "Je travaille seule pour vous offrir un moment de détente exclusif. Privilégiant toujours le soin en cours et le bien-être de la cliente présente, je ne peux pas toujours répondre au téléphone dans l'immédiat. <strong>La réservation en ligne est le moyen le plus sûr et rapide</strong> pour bloquer votre instant sans attendre de réponse humaine." },
    { q: "Comment expliquez-vous la valeur et la qualité de vos soins ?", r: "Mes tarifs reflètent une exigence stricte et une garantie de satisfaction. Ils incluent : un savoir-faire forgé sur <strong>18 ans d'expérience</strong>, l'utilisation exclusive de <strong>produits haut de gamme</strong>, et des résultats qui durent des semaines. Vous n'achetez pas seulement un soin : vous investissez dans une tenue impeccable, un véritable <strong>gain de temps</strong> au quotidien, et la certitude de repartir avec le sourire." },
    { q: "Quels services proposez-vous exactement ?", r: "L'Institut Lyne Beauty propose deux univers complets à Fribourg : l'onglerie (pose de gel, acrylique, vernis semi-permanent, pédicure spa, nail art) et la coiffure (tresses afro, draid, rasta, tissages, colorations, brushing, défrisage, coupe). Une expertise rare réunie dans un seul lieu." },
    { q: "Où se trouve l'institut de beauté ?", r: "L'Institut Lyne Beauty est situé au cœur de Fribourg, dans la vieille ville. Le salon est à 1 minute de l'arrêt du bus Bourg (lignes 2 et 6) et à 5 minutes à pied de la cathédrale Saint-Nicolas." },
    { q: "Quels moyens de paiement sont acceptés ?", r: "L'institut accepte les <strong>espèces (CHF)</strong>, les <strong>cartes bancaires</strong> (Maestro, V Pay, Mastercard, Visa), ainsi que les paiements <strong>sans contact</strong> et <strong>TWINT</strong>." },
  ],
  prestations: {
    onglerie: [
      { nom: "Première pose Gel", detail: "~ 1h30 min", prix: "85.—", cat: "gel" },
      { nom: "Remplissage Gel (4-5 sem.)", detail: "~ 60 min", prix: "65.—", cat: "gel" },
      { nom: "Remplissage Gel (-6 sem.)", detail: "~ 1h20 min", prix: "75.—", cat: "gel" },
      { nom: "Première pose Acrylique", detail: "~ 1h20 min", prix: "75.—", cat: "acrylique" },
      { nom: "Remplissage Acrylique (4-5 sem.)", detail: "~ 50 min", prix: "60.—", cat: "acrylique" },
      { nom: "Remplissage Acrylique (-6 sem.)", detail: "~ 1h10 min", prix: "70.—", cat: "acrylique" },
      { nom: "Manucure simple", detail: "~ 20 min", prix: "30.—", cat: "classique" },
      { nom: "Vernis semi-permanent", detail: "~ 40 min", prix: "45.—", cat: "classique" },
      { nom: "Supplément longueur extrême", detail: "Sur demande (Gel ou Acrylique)", prix: "+ 15.—", cat: "all" },
      { nom: "French, Baby-boomer, Nail Art", detail: "", prix: "dès 15.—", cat: "all" },
      { nom: "Réparation d'un ongle", detail: "", prix: "10.—", cat: "all" },
      { nom: "Retrait acrylique / gel", detail: "", prix: "30.—", cat: "all" },
      { nom: "Retrait vernis semi-permanent", detail: "", prix: "20.—", cat: "all" },
    ],
    pedicure: [
      { nom: "Vernis semi-permanent", detail: "~ 40 min", prix: "45.—" },
      { nom: "Gel ou acrylique", detail: "~ 55 min", prix: "60.—" },
      { nom: "Pédicure spa", detail: "Avec gommage & massage ~ 40 min", prix: "60.—" },
      { nom: "Pédicure spa + Semi-permanent", detail: "Avec gommage & massage ~ 60 min", prix: "90.—" },
      { nom: "Pédicure spa + Gel / Acrylique", detail: "Avec gommage & massage ~ 1h15 min", prix: "110.—" },
      { nom: "Pour plus de longueur", detail: "", prix: "dès 15.—" },
      { nom: "French / Nail Art", detail: "", prix: "dès 10.—" },
      { nom: "Retrait vernis semi-permanent", detail: "", prix: "15.—" },
      { nom: "Retrait gel ou acrylique", detail: "", prix: "25.—" },
    ],
    coiffure: [
      { nom: "Tresses draid", detail: "Avec extensions", prix: "dès 160.—", cat: "avec-ext" },
      { nom: "Tresses plaquées", detail: "Avec extensions", prix: "dès 100.—", cat: "avec-ext" },
      { nom: "2 grandes tresses plaquées", detail: "Avec extensions", prix: "50.—", cat: "avec-ext" },
      { nom: "Vanilles ou Twists", detail: "Avec extensions", prix: "dès 120.—", cat: "avec-ext" },
      { nom: "Tresses plaquées", detail: "Sans extensions", prix: "dès 50.—", cat: "sans-ext" },
      { nom: "2 grandes tresses plaquées", detail: "Sans extensions", prix: "45.—", cat: "sans-ext" },
      { nom: "Vanilles ou Twists", detail: "Sans extensions", prix: "dès 100.—", cat: "sans-ext" },
      { nom: "Barrels Twists", detail: "Sans extensions", prix: "dès 100.—", cat: "sans-ext" },
      { nom: "Serrer les locks ou rasta", detail: "Entretien", prix: "dès 160.—", cat: "soins" },
      { nom: "Tissage", detail: "Pose complète", prix: "dès 120.—", cat: "soins" },
      { nom: "Pose perruque", detail: "Ajustement sur-mesure", prix: "dès 60.—", cat: "soins" },
      { nom: "Chignon", detail: "Coiffure événement", prix: "dès 80.—", cat: "soins" },
      { nom: "Défrisage", detail: "Soin lissant", prix: "dès 80.—", cat: "soins" },
      { nom: "Couleur racine", detail: "Entretien couleur", prix: "dès 60.—", cat: "soins" },
      { nom: "Brushing", detail: "Mise en forme", prix: "dès 50.—", cat: "soins" },
      { nom: "Shampooing", detail: "Soin lavant profond", prix: "dès 20.—", cat: "soins" },
    ],
  },
};
